"""HTML Reporter — generates a self-contained styled HTML report."""
import os
from datetime import datetime
from scoring.risk_scorer import score_cloud

_HERE      = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(_HERE, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

SEV_COLOR = {
    "CRITICAL": "#e05555",
    "HIGH":     "#d97b3a",
    "MEDIUM":   "#c9a84c",
    "LOW":      "#4caf7d",
}


def save_html_report(resources: list, findings: list, cloud: str) -> str:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename  = os.path.join(OUTPUT_DIR, f"report_{cloud}_{timestamp}.html")

    scores = {
        c: score_cloud([r for r in resources if r.cloud == c])
        for c in {r.cloud for r in resources}
    }

    sev_counts = {}
    for f in findings:
        sev_counts[f.severity] = sev_counts.get(f.severity, 0) + 1

    findings_rows = ""
    for f in sorted(findings, key=lambda x: ["CRITICAL","HIGH","MEDIUM","LOW"].index(x.severity)):
        color = SEV_COLOR.get(f.severity, "#888")
        fws   = ", ".join(f.frameworks[:4])
        findings_rows += f"""
        <tr>
          <td style="color:{color};font-weight:700;font-family:monospace">{f.severity}</td>
          <td style="font-family:monospace;font-size:12px">{f.rule_id}</td>
          <td>{f.service}</td>
          <td>{f.resource_name}</td>
          <td>{f.message}</td>
          <td style="font-size:11px;color:#888">{fws}</td>
        </tr>"""

    score_cards = ""
    for c, s in scores.items():
        color = "#4caf7d" if s >= 80 else "#c9a84c" if s >= 60 else "#d97b3a" if s >= 40 else "#e05555"
        score_cards += f"""
        <div style="background:#1e2026;border:1px solid #2a2d35;border-radius:8px;
                    padding:20px 24px;display:inline-block;margin-right:16px;min-width:160px">
          <div style="font-size:40px;font-weight:700;color:{color}">{s}</div>
          <div style="color:#888;font-size:12px;margin-top:4px">{c.upper()} RISK SCORE</div>
        </div>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>CSPM Report — {cloud.upper()} — {datetime.now().strftime('%Y-%m-%d %H:%M')}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ background: #111214; color: #e8e8e8; font-family: 'Segoe UI', sans-serif;
           font-size: 14px; padding: 40px; }}
    h1 {{ font-size: 22px; letter-spacing: 0.05em; margin-bottom: 4px; }}
    h2 {{ font-size: 16px; color: #a0a0a8; margin: 32px 0 16px; letter-spacing: 0.04em; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 8px; }}
    th {{ background: #18191d; color: #a0a0a8; font-size: 11px; letter-spacing: 0.08em;
          padding: 10px 12px; text-align: left; border-bottom: 1px solid #2a2d35; }}
    td {{ padding: 10px 12px; border-bottom: 1px solid #1e2026; vertical-align: top; }}
    tr:hover td {{ background: #18191d; }}
    .badge {{ display:inline-block; padding:2px 8px; border-radius:3px; font-size:10px;
              font-weight:700; letter-spacing:0.06em; }}
  </style>
</head>
<body>
  <h1>Multi-Cloud CSPM Report</h1>
  <p style="color:#606068;font-size:13px;margin-top:4px">
    {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} · {cloud.upper()} · {len(resources)} resources · {len(findings)} findings
  </p>

  <h2>RISK SCORES</h2>
  {score_cards}

  <h2>FINDINGS SUMMARY</h2>
  <div style="display:flex;gap:16px;margin-bottom:8px">
    {''.join(f'<div style="background:#1e2026;border:1px solid #2a2d35;border-radius:6px;padding:12px 20px">'
             f'<div style="color:{SEV_COLOR[s]};font-size:24px;font-weight:700">{sev_counts.get(s,0)}</div>'
             f'<div style="color:#888;font-size:11px;margin-top:2px">{s}</div></div>'
             for s in ["CRITICAL","HIGH","MEDIUM","LOW"])}
  </div>

  <h2>ALL FINDINGS</h2>
  <table>
    <thead>
      <tr>
        <th>SEVERITY</th><th>RULE ID</th><th>SERVICE</th>
        <th>RESOURCE</th><th>MESSAGE</th><th>FRAMEWORKS</th>
      </tr>
    </thead>
    <tbody>{findings_rows}</tbody>
  </table>

  <p style="color:#444;font-size:11px;margin-top:40px">
    Generated by Multi-Cloud CSPM Tool v2.0
  </p>
</body>
</html>"""

    with open(filename, "w") as f:
        f.write(html)

    return filename
